dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - ".gitignore"
  - "requirements.txt"

  # Any typos we should ignore?
excluded_words:
  - typoci
  - onmousedown
  - onmouseup
  - ontouchend
  - ontouchstart


# Would you like filenames to also be spellchecked?
spellcheck_filenames: true