name: Electron Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build
        working-directory: ./server_client
        run: |
          yarn
          yarn build
      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: Build failed"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} -d '{"state": "failure", "description": "Build failed", "context": "Electron Build Check"}'
            exit 1
          else
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} -d '{"state": "success", "description": "Build succeeded", "context": "Electron Build Check"}'
          fi
